version: "3.3"
services:
  umfaka_core:
    image:  annona/umfaka_core:latest
    container_name: umfaka_core
    restart: always
    volumes:
      - ./conf:/app/conf
      - ./conf/.env:/app/.env
      - ./upload:/app/upload
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=${LOG_LEVEL}
      - SERVER_GIN_RUNMODE=${SERVER_GIN_RUNMODE}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_URL=${SERVER_URL}
      - SERVER_DB_REDIS_ADDRESS=${SERVER_DB_REDIS_ADDRESS}
      - SERVER_DB_TYPE=${SERVER_DB_TYPE}
      - SERVER_DB_HOST=${SERVER_DB_HOST}
      - SERVER_DB_PORT=${SERVER_DB_PORT}
      - SERVER_DB_ADDRESS=${SERVER_DB_ADDRESS}
      - SERVER_DB_USERNAME=${SERVER_DB_USERNAME}
      - SERVER_DB_PASSWORD=${SERVER_DB_PASSWORD}
      - SERVER_DB_NAME=${SERVER_DB_NAME}
      - CORE_API_TOKEN=${CORE_API_TOKEN}
      - BOT_MANAGER_ID=${BOT_MANAGER_ID}
      - CORE_API_URL=${CORE_API_URL}
      - BOT_TELEGRAM_TOKEN=${BOT_TELEGRAM_TOKEN}
      - BOT_TELEGRAM_WEBHOOK_URL=${BOT_TELEGRAM_WEBHOOK_URL}
      - PAYMENT_EPUSDT_API_ENABLE=${PAYMENT_EPUSDT_API_ENABLE}
      - PAYMENT_EPUSDT_API_URL=${PAYMENT_EPUSDT_API_URL}
      - PAYMENT_EPUSDT_API_KEY=${PAYMENT_EPUSDT_API_KEY}
      - PAYMENT_BTCPAY_API_ENABLE=${PAYMENT_BTCPAY_API_ENABLE}
      - PAYMENT_BTCPAY_API_URL=${PAYMENT_BTCPAY_API_URL}
      - PAYMENT_BTCPAY_API_KEY=${PAYMENT_BTCPAY_API_KEY}
      - PAYMENT_BTCPAY_API_STOREID=${PAYMENT_BTCPAY_API_STOREID}
      - PAYMENT_BTCPAY_API_WEBHOOK_SECRET=${PAYMENT_BTCPAY_API_WEBHOOK_SECRET}
      - PAYMENT_CRYPTAPI_API_ENABLE=${PAYMENT_CRYPTAPI_API_ENABLE}
      - PAYMENT_EASYPAY_API_ENABLE=${PAYMENT_EASYPAY_API_ENABLE}
      - PAYMENT_EASYPAY_API_URL=${PAYMENT_EASYPAY_API_URL}
      - PAYMENT_EASYPAY_API_PID=${PAYMENT_EASYPAY_API_PID}
      - PAYMENT_EASYPAY_API_KEY=${PAYMENT_EASYPAY_API_KEY}
      - PAYMENT_EASYPAY_REQUEST_BODY_ENCODE=${PAYMENT_EASYPAY_REQUEST_BODY_ENCODE}
      - PAYMENT_EASYPAY_API_DEVICE=${PAYMENT_EASYPAY_API_DEVICE}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
